### ISSUE TITLE
[bug report]已有值的情况下输入，须重新输入

### ISSUE THREAD

**Issue by yujiaaoyujia** [wusb/digital-keyboard#5]
因为如果一个输入操作是建立在已有值的情况下，这时候输入会从头输入，并且这个组件内的value并没有对外提供set方法，无法修改实际值
[建议]1.提供主动调用清除功能的api
2.提供一个option，可以设置初始值

另外，因为有需求用数字键盘输入金额，因此不能以0开头；本应该是很好实现的需求，例如输入00123，输入完后格式化实际值为123，但是因为不能控制内部value的值，再次点开数字键盘输入，会从之前的00123开始输入

**Comment by yujiaaoyujia** [comment]
刚刚发现value是可以改的
`const keyboard = new DigitalKeyboard()`
keyboard.value 的值可以修改，因此以上的问题可以解决

**Comment by simbawus** [comment]
嗯 后续我加个defaultValue API
